config-version = 2

after-startup-command = []
start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30
default-root-container-layout = 'tiles'
default-root-container-orientation = 'auto'

on-focused-monitor-changed = ['move-mouse monitor-lazy-center']
automatically-unhide-macos-hidden-apps = true

persistent-workspaces = ["1", "2", "3", "4", "5"]

[key-mapping]
preset = 'qwerty'

[gaps]
inner.horizontal = 8
inner.vertical   = 8
outer.left       = 8
outer.bottom     = 8
outer.top        = 8
outer.right      = 8

[mode.main.binding]
ctrl-alt-slash = 'layout tiles horizontal vertical'
ctrl-alt-comma = 'layout accordion horizontal vertical'

ctrl-alt-left  = 'focus --boundaries-action wrap-around-the-workspace left'
ctrl-alt-down  = 'focus --boundaries-action wrap-around-the-workspace down'
ctrl-alt-up    = 'focus --boundaries-action wrap-around-the-workspace up'
ctrl-alt-right = 'focus --boundaries-action wrap-around-the-workspace right'

ctrl-alt-shift-left  = 'move left'
ctrl-alt-shift-down  = 'move down'
ctrl-alt-shift-up    = 'move up'
ctrl-alt-shift-right = 'move right'

ctrl-alt-r = 'mode resize'

ctrl-alt-f = 'fullscreen'
ctrl-alt-shift-space = 'layout floating tiling'

ctrl-alt-1 = 'workspace 1'
ctrl-alt-2 = 'workspace 2'
ctrl-alt-3 = 'workspace 3'
ctrl-alt-4 = 'workspace 4'
ctrl-alt-5 = 'workspace 5'

ctrl-alt-shift-1 = 'move-node-to-workspace 1'
ctrl-alt-shift-2 = 'move-node-to-workspace 2'
ctrl-alt-shift-3 = 'move-node-to-workspace 3'
ctrl-alt-shift-4 = 'move-node-to-workspace 4'
ctrl-alt-shift-5 = 'move-node-to-workspace 5'

ctrl-alt-tab = 'workspace-back-and-forth'
ctrl-alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

ctrl-alt-shift-s = 'mode service'

[mode.resize.binding]
left  = 'resize width -50'
right = 'resize width +50'
down  = 'resize height +50'
up    = 'resize height -50'
enter = 'mode main'
esc   = 'mode main'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']
f = ['layout floating tiling', 'mode main']
backspace = ['close-all-windows-but-current', 'mode main']

ctrl-alt-shift-left  = ['join-with left', 'mode main']
ctrl-alt-shift-down  = ['join-with down', 'mode main']
ctrl-alt-shift-up    = ['join-with up', 'mode main']
ctrl-alt-shift-right = ['join-with right', 'mode main']
